# os:
#   - linux
#   - osx
#   - windows

language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      obs-studio

matrix:
  allow_failures:
    - rust: nightly

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
    - os: windows
