[package]
name = "motion-effects"
version = "0.1.0"
authors = ["Bennett Hardwick <me@bennetthardwick.com>"]
edition = "2018"

[dependencies]
obs-rs = { path = "../obs-rs", version = "0.1.0" }

[lib]
name = "motioneffects"
crate-type = ["cdylib"]
