name: Build OBS Plugins

on:
  push:
    branches:
      - master

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/target
          key: ubuntu-rust-target-directory
      - run: sudo apt-get install obs-studio libxcb-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --workspace
      - run: cargo build --release --workspace

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/target
          key: windows-rust-target-directory
      - run: choco install obs-studio
      - run: cargo test --workspace --exclude scroll-focus-filter
      - run: cargo build --release --workspace --exclude scroll-focus-filter

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/target
          key: macos-rust-target-directory
      - run: brew cask install obs
      - run: cargo test --workspace --exclude scroll-focus-filter
      - run: cargo build --release --workspace --exclude scroll-focus-filter
