name: Build OBS Plugins

on:
  push:
    branches:
      - master

# env:
#   FAIL_BUILD_IN_CI: true

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/target
          key: ubuntu-rust-target-directory
      - run: sudo apt-get install obs-studio libxcb-randr0-dev libxcb-ewmh-dev llvm
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo test --workspace
          cargo build --release --workspace

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/target
          key: windows-rust-target-directory
      - run: |
          choco install obs-studio llvm
          cargo test --workspace --exclude scroll-focus-filter
          cargo build --release --workspace --exclude scroll-focus-filter

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/target
          key: macos-rust-target-directory
      - run: |
          brew install llvm
          brew link --force llvm
          brew cask install obs
          cargo test --workspace --exclude scroll-focus-filter
          cargo build --release --workspace --exclude scroll-focus-filter
